### PR TITLE
Color change of booking card depending on decision

### PR DESCRIPTION
**Pull request by julien4215**
Color of the booking card changed to green if the request is accepted and red if the request is declined.

### CODE REVIEW

**Comment by julien4215** [comment]
Capture d’écran du 2023-08-24 23-33-51

**Comment by julien4215** [comment]
With the gradient
Capture d’écran du 2023-08-25 01-02-04

**Review by Rotheem — APPROVED** [review]

**Comment by julien4215** [comment]
With the new green gradient and box shadow
Capture d’écran du 2023-08-25 12-55-08

**Comment by julien4215** [comment]
Screenshot of the booking card from the last commit

image

**Review by Rotheem — APPROVED** [review]

**Review by armanddidierjean — APPROVED** [review]
This is lovely! Thank you for the contribution!

**Pull request merged**
