### PR TITLE
Replace all host and Repository.displayHost with Repository.host

### LINKED ISSUE #444: Remove displayHost-related stuff
Since Titan makes requests to its host only (and fonts.gstatic.com but anyway), the host-displayHost distinction introduced [here](https://github.com/aeecleclair/Titan/blob/318f0b3a09b1f8a4a54a8bd5a725a5df70d6de35/lib/tools/repository/repository.dart#L11-L13) is obsolete.

Discovered when trying to solve #436 by replacing `"myecl.fr"` with smth else (see my comment at that issue).

### PR DESCRIPTION
**Pull request by Marc-Andrieu**
Fix #444
However, the `decode` argument in getOne seems useless: now it's an unused argument, and its only appearance was here
https://github.com/aeecleclair/Titan/blob/318f0b3a09b1f8a4a54a8bd5a725a5df70d6de35/lib/tools/repository/repository.dart#L116
which evaluates to `true || decode` which is true no matter the value of `decode`

### CODE REVIEW

**Comment by Marc-Andrieu** [comment]
Making `host` a static string makes it impossible to override, so Centralisation is broken.

I hesitate between three solutions regarding the short file https://github.com/aeecleclair/Titan/blob/main/lib/centralisation/repositories/section_repository.dart:
* Not extending it from `Repository` in the first place: the `Repository` class is too complex (tokens, host, endpoints, etc), because it's made to handle the responses of a complete API. Here we just want to get a JSON file.
* Still extending it from `Repository`, but using native `http.get` instead of `getOne`. But some exception handling should be written for Centralisation. Also, not using `getOne` in this _short_ file makes it useless to extend from `Repository`
* Asking Hyperion to get it for us. The only negative part is that it may be a bit slower for the UX. But we would keep using `getOne`, and https://centralisation.eclair.ec-lyon.fr would not be hard-coded anymore (well actually it's also in the constant `imagePath`)

**Comment by Marc-Andrieu** [comment]
BTW, notice the rare cases of requests not to Hyperion (namely for the fonts, Centralisation's SVG files, for Plausible, etc) do not use methods of `Repository` so the 1st solution seems OK (and there are few possible error when not receiving the JSON).

**Review by maximeroucher — APPROVED** [review]
The last option is best in terms of practices, however, it will require a lot f work for only one endpoint, which is a bit overkill.
Consider going for it if multiple services a being handled this way (we already change the cinéma module for instance)

**Review by Rotheem — APPROVED** [review]

**Comment by Marc-Andrieu** [comment]
Just for reference: `http.get()` always follows redirections (one has to use smth more advanced like `HttpClient` to disable following redirections)

**Comment by Marc-Andrieu** [comment]
Sh*t I forgot to switch to "Rebase" before clicking on that button

**Pull request merged**
