### PR TITLE
fix: adding missing tokenExpireWrapper

### PR DESCRIPTION
**Pull request by maximeroucher**
Goal of this PR : 

Description of the added features :
- [ ]

Required unmerged PR :
- [ ]

Images (if the PR changes the front) :

| Desktop | Mobile |
| ------- | ------ |
|         |        |

Other informations :
-

### CODE REVIEW

**Review by julien4215 — COMMENTED** [review]
Would it make sense to move these `tokenExpireWrapper` to repository calls instead ?

**Comment by maximeroucher** [comment]
> Would it make sense to move these `tokenExpireWrapper` to repository calls instead ?

It will require passing ref to repository, which is quite annoying to do

**Comment by julien4215** [comment]
Sorry wanted to say to api calls that are made in providers

**Comment by maximeroucher** [comment]
Could be a good idea

**Review by Marc-Andrieu — APPROVED** [review]
Every call to the backend correctly wrapped

**Pull request merged**
