### PR TITLE
Remove windows folder

### PR DESCRIPTION
**Pull request by julien4215**
We should remove the windows folder as we are not supporting this platform.

### CODE REVIEW

**Comment by maximeroucher** [comment]
Maybe consider gitignoring the folder to make sure it does not get included on another commit

**Review by guillaumetavernier — APPROVED** [review]

**Comment by julien4215** [comment]
> Maybe consider gitignoring the folder to make sure it does not get included on another commit

I don't see why fluttter would regenerate the windows folder but if it does then we can gitignore it.

**Comment by julien4215** [comment]
Yes but why someone would build this project with windows ?

**Comment by guillaumetavernier** [comment]
> Yes but why someone would build this project with windows ?
> 

It happens to the best of us 🙄
(It's often the default option while compiling on VS Code)

**Comment by julien4215** [comment]
Does it still give the option without the windows folder ? I can't try because I only have Flutter on Linux.
Also does it allow you to build on windows even if there is no windows folder in the project ?

**Comment by maximeroucher** [comment]
Building for windows without having the folder will generate it

**Comment by julien4215** [comment]
Ok I added it to the .gitignore

**Review by maximeroucher — APPROVED** [review]

**Pull request merged**
